name: VNC Server Installation

on: workflow_dispatch

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Install VNC Server
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -off -restart -agent -privs -all -allowAccessFor -specifiedUsers
    - name: Allow access for admin user
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -users admin -access -on -privs -all
    - name: Start VNC Server
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -specifiedUsers -restart -agent -privs -all -users admin
    - name: Create Tunnel
      run: ./ngrok tcp 5900