name: RDP MacOS

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Download
      run: curl -LO https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip
    - name: Extract
      run: unzip ngrok-v3-stable-darwin-amd64.zip
    - name: Auth
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP
      run: sudo systemsetup -setremotelogin on
    - name: Who I
      run: whoami
    - name: download passwd
      run: git clone https://github.com/BROILYA091/rdp
    - name: Copy passwd
      run: mv rdp/passwd.sh passwd.sh
    - name: Run passwd
      run: sudo sh passwd.sh
    - name: Create Tunnel
      run: ./ngrok tcp 3389
