name: VNC Server Installation

on: workflow_dispatch

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Download
      run: curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-darwin-amd64.zip
    - name: Extract
      run: unzip ngrok-stable-darwin-amd64.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Create vnc-mac user 1
      run: sudo dscl . -create /Users/vnc-mac
    - name: Create vnc-mac user 2
      run: sudo dscl . -create /Users/vnc-mac UserShell /bin/bash
    - name: Create vnc-mac user 3
      run: sudo dscl . -create /Users/vnc-mac RealName "VNC User"
    - name: Create vnc-mac user 4    
      run: sudo dscl . -create /Users/vnc-mac UniqueID "1001"
    - name: Create vnc-mac user 5
      run: sudo dscl . -create /Users/vnc-mac PrimaryGroupID 20
    - name: Create vnc-mac user 6
      run: sudo dscl . -create /Users/vnc-mac NFSHomeDirectory /Users/vnc-mac
    - name: Create vnc-mac user 7
      run: sudo dscl . -passwd /Users/vnc-mac q1qq1q
    - name: Install VNC Server
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -off -restart -agent -privs -all -allowAccessFor -specifiedUsers
    - name: Allow access for admin user
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -users admin -access -on -privs -all
    - name: KickStart started
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes
    - name: Start VNC Server
      run: sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -specifiedUsers -restart -agent -privs -all -users admin,vnc-mac
    - name: Create Tunnel
      run: ./ngrok tcp 5900