name: MacOs 2

on: workflow_dispatch

jobs:
 build:

 runs-on: macos-latest

 steps:
 - name: Download
   run: curl -O https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-darwin-amd64.zip
 - name: Extract
   run: unzip ngrok-stable-darwin-amd64.zip
 - name: Auth
   run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
   env:
     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
 - name: Enable TS
   run: sudo systemsetup -setremotelogin on
 - run: sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist
 - run: sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
 - run: sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.RemoteDesktop.PrivilegeProxy.plist
 - run: sysadminctl -addUser runneradmin -password "Hello.world01@" -admin
 - name: Create Tunnel
   run: ./ngrok/ngrok tcp 3389
