name: Ubuntu Linux

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -O ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok/ngrok authtoken $NGROKAUTHTOKEN
      env:
        NGROKAUTHTOKEN: ${{ secrets.NGROKAUTHTOKEN }}
    - name: Enable SSH
      run: sudo ufw allow 22
    - name: Create Tunnel
      run: ./ngrok/ngrok tcp 22
